version: '3.8'

services:
  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432