"""Creating initial tables

Revision ID: ca070566b706
Revises: 
Create Date: 2022-01-24 13:05:56.530403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca070566b706'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('data_started', sa.Date(), nullable=False),
    sa.Column('date_to_be_finished', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('priority', sa.Boolean(), nullable=False),
    sa.Column('id_installments', sa.Integer(), nullable=False),
    sa.Column('id_kind', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_installments'], ['Installments.id'], ),
    sa.ForeignKeyConstraint(['id_kind'], ['Kind.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_account'], ['Account.id'], ),
    sa.ForeignKeyConstraint(['id_transaction'], ['Transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Balance')
    op.drop_table('Transactions')
    op.drop_table('Account')
    op.drop_table('User')
    op.drop_table('Kind')
    op.drop_table('Installments')
    # ### end Alembic commands ###
